-- 用户问题反馈表
CREATE TABLE CMJT_FEEDBACK_ISSUE (
    ID              VARCHAR2(36)    NOT NULL,
    TITLE           VARCHAR2(200)   NOT NULL,
    QUESTION_CONTENT VARCHAR2(2000) NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'OPEN' NOT NULL,
    USER_ID         VARCHAR2(36)    NOT NULL,
    USER_NAME       VARCHAR2(100),
    ADMIN_REPLY     VARCHAR2(2000),
    REPLY_ADMIN_ID  VARCHAR2(36),
    REPLY_ADMIN_NAME VARCHAR2(100),
    REPLY_TIME      DATE,
    CLOSE_BY        VARCHAR2(36),
    CLOSE_BY_NAME   VARCHAR2(100),
    CLOSE_TIME      DATE,
    CREATED_BY      VARCHAR2(36),
    CREATION_DATE   DATE,
    LAST_UPDATED_BY VARCHAR2(36),
    LAST_UPDATE_DATE DATE,
    ORG_IDENTITY    VARCHAR2(255),
    CONSTRAINT PK_CMJT_FEEDBACK_ISSUE PRIMARY KEY (ID)
);

CREATE INDEX IDX_CMJT_FEEDBACK_USER ON CMJT_FEEDBACK_ISSUE (USER_ID);
CREATE INDEX IDX_CMJT_FEEDBACK_STATUS ON CMJT_FEEDBACK_ISSUE (STATUS);
